### ISSUE TITLE
Missing support for Cocoapods

### ISSUE THREAD

**Issue by tylerjames** [box/box-ios-browse-sdk#131]
Hey devs,

Is there a reason you don't still support Cocoapods? I realize for a brand new project someone might decide to use Carthage over Cocoapods, but my current project already has several pods and it's pretty tedious to  have to add Carthage as well just for this one library.

Any chance of adding Cocoapods support again?

**Comment by jdizoglio** [comment]
Hi Tyler, The SDK's are dynamic frameworks and can be included in podfiles. Should work with the latest pod version and then access nicely from your project as a module. However, carthage and pods are compatible and will most likely be a quick route to success. After you execute cathage, you configure your xcode framework (drag and drop) and then use import <module> (same as pods). It's also nice, because you don't get all the pod artifacts hidden in your project.

In-house, after execute carthage with submodule, we add the checked out dependency project to our main app project. Makes it easy to debug and update.

**Comment by tylerjames** [comment]
Thanks for the info. I managed to get it going, I was missing the steps about adding the post-build script to copy just the relevant files from the framework.

I actually just attended BoxWorks in San Francisco, looks like you guys are up to an impressive amount of stuff. Box Skills looks super cool, very interested to see how it works in real life.
